### ISSUE TITLE
Use ocrd file handling facilities for ocrd processors

### ISSUE THREAD

**Issue by wrznr** [syedsaqibbukhari/docanalysis#32]
Many thanks for your efforts to meet the ocrd interfaces for your tools. However, using the file handling facilities of 3rd party libraries as `ocrolib` and `cv` does not work in the general case. You start out correctly at https://github.com/syedsaqibbukhari/docanalysis/blob/4d30afc70f6f515febe11af914e63e0296e74cba/ocrd_anybaseocr/cli/ocrd_anybaseocr_cropping.py#L409
but at https://github.com/syedsaqibbukhari/docanalysis/blob/4d30afc70f6f515febe11af914e63e0296e74cba/ocrd_anybaseocr/cli/ocrd_anybaseocr_cropping.py#L414 and https://github.com/syedsaqibbukhari/docanalysis/blob/4d30afc70f6f515febe11af914e63e0296e74cba/ocrd_anybaseocr/cli/ocrd_anybaseocr_cropping.py#L68 you contradict your own efforts which results in
```shell
$ ocrd-anybaseocr-crop -I ORIGINAL -O CROPPED_DFKI -m mets.xml 
Process file:  https://digital.slub-dresden.de/data/kitodo/GottDie_453779263/GottDie_453779263_tif/jpegs/00000001.tif.original.jpg
Traceback (most recent call last):
  File "/home/kmw/Documents/Work/OCR-D/env/bin/ocrd-anybaseocr-crop", line 10, in <module>
    sys.exit(ocrd_anybaseocr_cropping())
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/ocrd_anybaseocr/cli/cli.py", line 12, in ocrd_anybaseocr_cropping
    return ocrd_cli_wrap_processor(OcrdAnybaseocrCropper, *args, **kwargs)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/ocrd/decorators.py", line 38, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/ocrd/processor/base.py", line 65, in run_processor
    processor.process()
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/ocrd_anybaseocr/cli/ocrd_anybaseocr_cropping.py", line 414, in process
    binImg = ocrolib.read_image_binary(fname)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/ocrolib/toplevel.py", line 224, in argument_checks
    result = f(*args,**kw)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/ocrolib/common.py", line 209, in read_image_binary
    pil = PIL.Image.open(fname)
  File "/home/kmw/Documents/Work/OCR-D/env/lib/python3.6/site-packages/PIL/Image.py", line 2634, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'https://digital.slub-dresden.de/data/kitodo/GottDie_453779263/GottDie_453779263_tif/jpegs/00000001.tif.original.jpg'
```
when using URLs instead of local file references.

**Comment by wrznr** [comment]
https://github.com/syedsaqibbukhari/docanalysis/pull/33 solves this somehow for cropping (as far as I understood your cropping approach). Has to be carried over to the other operations.

**Comment by mjenckel** [comment]
we got slightly confused with #33, because it didnt have any apparent changes to cropping, until we noticed that the last commit to #33 (53cfe81) does not contain the changes while the first commit (ea6d1d3) does

**Comment by kba** [comment]
@mjenckel Just a quick tip: To see changes without whitespace in git, use the `-b` flag or in GitHub, append `?w=1`. E.g. https://github.com/syedsaqibbukhari/docanalysis/pull/33/commits/ea6d1d3ac69a97dfb8371f1bfee4c9cb9ebfdb62?w=1 for the changes to business logic.
