### ISSUE TITLE
Error on make test-crop

### ISSUE THREAD

**Issue by kba** [syedsaqibbukhari/docanalysis#38]
```sh
$ make test-crop
[...]
Process file:  OCR-D-IMG/becker_quaestio_1586_00013.tiff
Traceback (most recent call last):
  File "/data/monorepo/venv3.6/bin/ocrd-anybaseocr-crop", line 11, in <module>
    load_entry_point('ocrd-anybaseocr', 'console_scripts', 'ocrd-anybaseocr-crop')()
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/data/monorepo/docanalysis/ocrd_anybaseocr/cli/cli.py", line 13, in ocrd_anybaseocr_cropping
    return ocrd_cli_wrap_processor(OcrdAnybaseocrCropper, *args, **kwargs)
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/ocrd/decorators.py", line 38, in ocrd_cli_wrap_processor
    run_processor(processorClass, ocrd_tool, mets, workspace=workspace, **kwargs)
  File "/data/monorepo/venv3.6/lib/python3.6/site-packages/ocrd/processor/base.py", line 65, in run_processor
    processor.process()
  File "/data/monorepo/docanalysis/ocrd_anybaseocr/cli/ocrd_anybaseocr_cropping.py", line 415, in process
    img_array_rr = self.remove_rular(img_array)
  File "/data/monorepo/docanalysis/ocrd_anybaseocr/cli/ocrd_anybaseocr_cropping.py", line 69, in remove_rular
    arg, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'
```

**Comment by wrznr** [comment]
Fixed in #42 !
